spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: config
          configMap:
            name: ${project.artifactId}-config
            items:
              - key: application.properties
                path: application.properties
      containers:
        - volumeMounts:
            - name: config
              mountPath: /home/quarkus/config
          resources:
            limits:
              memory: 64Mi
              cpu: 500m
          envFrom:
            - secretRef:
                name: ${project.artifactId}-secret